import { GridColDef } from "@mui/x-data-grid";
export const pageSizeManageQuiz = 12;
export const rowsManageStudent = [
  {
    id: 1,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 2,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 3,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 4,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 5,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 6,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 7,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 8,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 9,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 10,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 11,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 12,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
  {
    id: 13,
    lastName: "abduljabbar",
    firstName: "rana",
    userName: "rana.abduljabbar",
    yog: "2024",
    program: "COP",
    email: "rana.abduljabbar@my.rfums.org",
  },
];
