const QUERY_KEYS = {
  QUIZ: "QUIZ",
  QUIZ_NO: "QUIZ_NO",
  QUIZ_BY_ID: "QUIZ_BY_ID",
  COURSES_LISTING: "COURSES_LISTING",
  FOLDER_LISTING: "FOLDER_LISTING",
  SCORING_LISTING: "SCORING_LISTING",
  SCORING_BY_ID: "SCORING_BY_ID",
  QUIZ_DISTRIBUTE: "QUIZ_DISTRIBUTE",
  QUIZ_SAVE: "QUIZ_SAVE",

  // Take Quiz
  TAKE_QUIZ: "TAKE_QUIZ",
  TAKE_QUIZ_COURSES_LISTING: "TAKE_QUIZ_COURSES_LISTING",
  QUES_QUIZ_BY_ID: "QUES_QUIZ_BY_ID",
};

export default QUERY_KEYS;
