const QUERY_KEYS = {
  QUIZ_NO: "QUIZ_NO",
  QUIZ_BY_ID: "QUIZ_BY_ID",
  COURSES_LISTING: "COURSES_LISTING",
  FOLDER_LISTING: "FOLDER_LISTING",
  SCORING_LISTING: "SCORING_LISTING",
  SCORING_BY_ID: "SCORING_BY_ID",
};

export default QUERY_KEYS;
